#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=0.13.29

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/sdk

COPY target/repomarket.dar /home/sdk/

EXPOSE 6865

CMD ~/.daml/bin/daml sandbox -- --port 6865 repomarket.dar
